# Generated by Django 5.0.3 on 2024-05-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caategory',
            new_name='Category',
        ),
    ]
